services: #list of services
  static_html: #custom key name
    build:
      context: ./static_html #where you want to build
      dockerfile: static.Dockerfile   #your docker file
    ports:
      - 8000:8000 #port mapping
      - 3000:8000
    command: python -m http.server 8000