services: #list of services
  backend: #custom key name
    build:
      context: ./backend #where you want to build
      dockerfile: Dockerfile   #your docker file
    ports:
      - 8080:8000 #port mapping
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - PORT=8000
      - MY_PROJECT=Hello World
    env_file:
      - .env
    volumes:
      - ./backend/src:/app
    # depends_on:
    #   - db
    develop:
      watch:
        - action: rebuild
          path: ./backend/requirements.txt
        - action: rebuild
          path: ./backend/Dockerfile
        - action: restart
          path: ./backend/src
          # target: /app

  # DATABASE_URL=postgresql+psycopg://username:password@dbhost:dbport/dbname
  # db:
  #   image: postgres:17.5
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=local_db
  #   volumes:
  #     - dc_managed_db_volume:/var/lib/postgresql/data
  static_html: #custom key name
    build:
      context: ./static_html #where you want to build
      dockerfile: static.Dockerfile   #your docker file
    ports:
      - 8000:8000 #port mapping
      - 3000:8000
    command: python -m http.server 8000
    volumes:
      - ./static_html/src:/app

# volumes:
#   dc_managed_db_volume: {}